#version: "3.3"
services:
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=burger
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=QwsAzx

  frontend:
    container_name: frontend
    build:
      context: frontend
    volumes:
      - .:/star-burger/staticfiles/

  backend:
    container_name: backend
    build:
      context: backend
    volumes:
      - .:/star-burger/staticfiles/
      - .:/star-burger/media/
    command: >
      bash -c "gunicorn -w 3 -b 0.0.0.0:8080 star_burger.wsgi:application"
    environment:
      - DEBUG=TRUE
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - db

volumes:
  staticdir:
  db_data:
  mediadir: