version: "2.29.7"
services:
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=burger
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=QwsAzx

  frontend:
    image: star-burger_frontend:v1.0
    container_name: star-burger_frontend
    build:
      context: ./frontend
      target: frontend
    volumes:
      - staticdir:/usr/app/frontend/staticfiles

  static:
    image: star-burger_static:v1.0
    build:
      context: ./backend
      target: static
    volumes:
      - staticdir:/usr/app/staticfiles

  gunicorn:
    image: star-burger_gunicorn:v1.0
    build:
      context: ./backend
      target: gunicorn
    volumes:
      - staticdir:/usr/app/staticfiles
      - mediadir:/usr/app/media
    environment:
      - DATABASE_URL=${DATABASE_URL-postgres://admin:QwsAzx@db:5432/burger}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS-194.58.126.247,127.0.0.1,localhost}
      - DEBUG=True
    env_file:
      - ./.env
    ports:
      - "194.58.126.247:8080:8080"
    depends_on:
      - static
      - db

  nginx:
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - staticdir:/usr/app/staticfiles
      - mediadir:/usr/app/media
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - gunicorn
      - db
    restart: always

volumes:
  staticdir:
  db_data:
  mediadir: