version: "3.3"
services:
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=burger
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=QwsAzx

  frontend:
    image: star-burger_frontend:v1.0
    container_name: star-burger_frontend
    build:
      context: frontend
      dockerfile: ./frontend/Dockerfile
    volumes:
      - staticdir:/usr/app/frontend/staticfiles

  static:
    image: star-burger_static:v1.0
    build:
      context: backend
      dockerfile: ./backend/Dockerfile
    volumes:
      - staticdir:/usr/app/staticfiles
      - mediadir:/usr/app/media
    command: >
      bash -c "gunicorn -w 3 -b 0.0.0.0:8080 star_burger.wsgi:application"
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - db

volumes:
  staticdir:
  db_data:
  mediadir: